"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const urlPlayerController_1 = require("../controller/urlPlayerController");
const renovacaoController_1 = require("../controller/renovacaoController");
const notificacaoController_1 = require("../controller/notificacaoController");
const listaController_1 = require("../controller/listaController");
const urlController_1 = require("../controller/urlController");
const apkDownload_1 = require("../controller/apkDownload");
const PlayerApi_1 = require("../controller/PlayerApi");
const xmltv_1 = require("../controller/xmltv");
const express_1 = require("express");
const router = (0, express_1.Router)();
router.post('/notificacoes', notificacaoController_1.notificacaopix);
router.get('/renovar/:login', renovacaoController_1.RenovacaoController);
router.get('/apk', apkDownload_1.apkDownload);
router.get('/lista/:provedor/:login', listaController_1.listaController);
router.get('/url/:provedor/:media/:login/:video', urlController_1.urlController);
router.get('/:media/:user/:password/:video', urlPlayerController_1.urlPlayerController);
router.get(['/player_api.php', '/panel_api.php'], PlayerApi_1.PlayerApi);
router.get('/xmltv.php', xmltv_1.xmltv);
exports.default = router;
